# Database related constants
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_TYPE = 'DATABASE_TYPE'
DATABASE_PATH = 'DATABASE_PATH'
DATABASE_HOST = 'DATABASE_HOST'
DATABASE_URL = 'DATABASE_URL'
DATABASE_USERNAME = 'DATABASE_USERNAME'
DATABASE_PASSWORD = 'DATABASE_PASSWORD'
